[VE] Intrinsics for vector logical 2-operand instructions
sx-aurora-dev/llvm-project pull request #25
Opened 2021-03-12 21:28 UTC by akmaru

Added the builtins and  LLVM-IR intrinsics for vpcnt, vldz and vbrv instructions.

2021-03-13 03:13 UTC, LWisteria commented
We've used vpcnt on our project. This PR works fine!

2021-03-15 10:28 UTC, kaz7 requested changes
Thank you for contribution.  I've checked modified llvm for ve using internal test suites, and it works fine.  Thank you so much.  I need to ask you to fix a few typo.  May I ask you to remove these spaces?

2021-03-15 10:28 UTC, kaz7 commented on llvm/lib/Target/VE/veintrin.py
> +
Please remove spaces here.

2021-03-15 10:28 UTC, kaz7 commented on llvm/lib/Target/VE/veintrin.py
> +
Please remove this line (modify two empty lines into single empty line and remove spaces from empty lines)

2021-03-18 08:29 UTC, merged

2021-03-18 08:31 UTC, kaz7 commented
Well, I've merged and cleaned code like above description.  Thank you very much for your contributions.

2021-03-19 01:46 UTC, akmaru commented
Thank you reviewing and fix!